/***

Name: Addresses

Description:This class has been used in HouseHoldContactAddressCreation and  DateRange class.This is like object structure where we can store address details.


Created Date: 20th May 2017

***/


Global class Addresses{
      Public String street;
      Public String city;
      Public String state;
      Public String country;
      Public String postalcode;
      Public String start_date;
      Public String end_date;
      
     
      
      }